version: '2'
services:
  elasticsearch:
    image: elasticsearch:5.6
    container_name: elasticsearch
    ports:
      - 9200:9200
    volumes:
      - ./es/data:/usr/share/elasticsearch/data
      - ./es/config:/usr/share/elasticsearch/config

  kibana:
    image: kibana:5.6
    container_name: kibana
    ports:
      - 5601:5601
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200

  skywalking:
      build:
        context: .
        dockerfile: ./skywalking/dockerfile
      container_name: skywalking
      ports:
        - 10800:10800
        - 11800:11800
        - 12800:12800
        - 8090:8080
      links:
        - elasticsearch:elasticsearch
      depends_on:
        - elasticsearch